#!/usr/bin/env python3
"""Materialize c2hls-ready AutoSA DSE packages (gold/baseline/TB/TCL)."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from scripts.autosa_dse_hls_common import (  # noqa: E402
    DEFAULT_CLOCK_NS,
    DEFAULT_DEVICE_PLATFORM,
    DEFAULT_PART,
    _write_manifest,
    emit_autosa_dataset_tcls,
    iter_export_packages,
)

DEFAULT_SOURCES = REPO / "AutoSA_sources"
DEFAULT_OUT = REPO / "benchmarks_autosa_dse"

# Core c2hls inputs (no logs / hls_prj).
PACKAGE_FILES = (
    "plain.cpp",
    "gold_hls_source.cpp",
    "hls_baseline.cpp",
    "kernel.h",
    "kernel_kernel.h",
    "kernel_kernel_modules.cpp",
    "testbench.cpp",
    "provenance.json",
    "hls_validate.json",
)
COSIM_FILES = (
    "hls_baseline_cosim.cpp",
    "testbench_cosim.cpp",
)
LEGACY_TCL = (
    "run_csim.tcl",
    "run_synth.tcl",
    "hls_script.tcl",
)


def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _bench_id(src_pkg: Path) -> str:
    """autosa_mm/rank1_latency_4760 -> autosa_mm_rank1"""
    kernel = src_pkg.parent.name
    rank = src_pkg.name.split("_")[0]
    return f"{kernel}_{rank}"


def _symlink_or_copy(src: Path, dst: Path) -> None:
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    if src.resolve() == dst.resolve():
        return
    try:
        os.symlink(src.resolve(), dst)
    except OSError:
        shutil.copy2(src, dst)


def _write_gold_kernel_for_cosim(pkg_dir: Path) -> None:
    cosim_kernel = pkg_dir / "hls_baseline_cosim.cpp"
    if not cosim_kernel.is_file():
        return
    dst = pkg_dir / "gold_kernel_for_cosim.cpp"
    header = (
        "// AUTO-GENERATED by prepare_autosa_dse_c2hls.py — do not edit.\n"
        "// Identical to hls_baseline_cosim.cpp for cosim gold-gate pre-check.\n\n"
    )
    body = cosim_kernel.read_text(encoding="utf-8")
    dst.write_text(header + body, encoding="utf-8")


def _write_legacy_tcls(pkg_dir: Path, *, clock_ns: float) -> None:
    """Refresh export-time TCL with kernel.h on testbench path."""
    kernel_files = [
        "add_files kernel_kernel.h",
        "add_files hls_baseline.cpp",
    ]
    common = [
        "open_project hls_prj",
        "set_top kernel0",
        *kernel_files,
        f'open_solution "solution1" -flow_target vitis',
        f"set_part {{{DEFAULT_PART}}}",
        f"create_clock -period {clock_ns} -name default",
        "config_compile -name_max_length 50",
    ]
    (pkg_dir / "run_csim.tcl").write_text(
        "\n".join(
            [
                *common,
                "add_files -tb testbench.cpp",
                "add_files -tb kernel.h",
                "csim_design",
                "exit",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    (pkg_dir / "run_synth.tcl").write_text(
        "\n".join([*common, "csynth_design", "exit"]) + "\n",
        encoding="utf-8",
    )
    (pkg_dir / "hls_script.tcl").write_text(
        "\n".join(
            [
                *common,
                "add_files -tb testbench.cpp",
                "add_files -tb kernel.h",
                "csim_design",
                "csynth_design",
                "exit",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


def _patch_metadata(
    meta: dict,
    *,
    bench_id: str,
    src_pkg: Path,
    validate: dict | None,
    tcl_paths: dict[str, str],
    has_cosim: bool,
) -> dict:
    meta = json.loads(json.dumps(meta))
    meta["corpus"] = "benchmarks_autosa_dse"
    meta["c2hls_bench_id"] = bench_id
    meta["c2hls_ready"] = True
    meta["c2hls_prepared_at"] = _utc_now()
    meta["gold_hls_source_file"] = "gold_hls_source.cpp"
    meta["gold_hls_baseline_file"] = "hls_baseline.cpp"
    meta["plain_c_file"] = "plain.cpp"
    meta["testbench_file"] = "testbench.cpp"
    # Keep modules.cpp on disk for provenance, but never stage it for HLS:
    # gold/baseline already embed the module definitions.
    support = [
        rel
        for rel in (meta.get("support_files") or [])
        if Path(rel).name != "kernel_kernel_modules.cpp"
    ]
    if "kernel_kernel.h" not in support and (src_pkg / "kernel_kernel.h").is_file():
        support.insert(0, "kernel_kernel.h")
    meta["support_files"] = support
    meta["dataset_hls_tcl"] = "dataset_hls.tcl"
    meta["dataset_hls_csim_tcl"] = "dataset_hls_csim.tcl"
    meta["source_package"] = str(src_pkg.resolve())
    meta["target_part"] = meta.get("target_part", DEFAULT_PART)
    meta["target_clock_ns"] = meta.get("target_clock_ns", DEFAULT_CLOCK_NS)
    meta["target_device_platform"] = meta.get("target_device_platform", DEFAULT_DEVICE_PLATFORM)

    if validate:
        meta["c2hls_validate_status"] = validate.get("status")
        meta["c2hls_validate_mode"] = validate.get("validate_mode") or validate.get(
            "cosim_skipped_reason"
        )
        if validate.get("cosim_skipped_reason"):
            meta["cosim_skipped_reason"] = validate["cosim_skipped_reason"]

    if has_cosim:
        meta["supports_cosim"] = True
        meta["cosim_kernel_file"] = "hls_baseline_cosim.cpp"
        meta["cosim_testbench_file"] = "testbench_cosim.cpp"
        meta["cosim_support_files"] = ["gold_kernel_for_cosim.cpp"]
        meta["dataset_hls_cosim_tcl"] = "dataset_hls_cosim.tcl"
        depths = meta.get("cosim_depths") or {}
        prov = meta.get("provenance") or {}
        if not depths and prov.get("c2hls_cosim_depths"):
            meta["cosim_depths"] = prov["c2hls_cosim_depths"]
    else:
        meta.setdefault("supports_cosim", False)

    meta["tcl_files"] = {
        "dataset_hls": "dataset_hls.tcl",
        "dataset_hls_csim": "dataset_hls_csim.tcl",
        **({"dataset_hls_cosim": "dataset_hls_cosim.tcl"} if has_cosim else {}),
        "legacy": list(LEGACY_TCL),
    }
    return meta


def prepare_package(
    src_pkg: Path,
    dst_pkg: Path,
    *,
    link: bool = True,
    in_place: bool = False,
) -> dict:
    src_pkg = src_pkg.resolve()
    work_dir = src_pkg if in_place else dst_pkg
    if not in_place:
        work_dir.mkdir(parents=True, exist_ok=True)
        for name in PACKAGE_FILES:
            src = src_pkg / name
            if src.is_file():
                if link:
                    _symlink_or_copy(src, work_dir / name)
                else:
                    shutil.copy2(src, work_dir / name)
        for name in COSIM_FILES:
            src = src_pkg / name
            if src.is_file():
                if link:
                    _symlink_or_copy(src, work_dir / name)
                else:
                    shutil.copy2(src, work_dir / name)

    meta_path = work_dir / "metadata.json"
    if meta_path.is_file():
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
    else:
        meta = json.loads((src_pkg / "metadata.json").read_text(encoding="utf-8"))

    validate = None
    val_path = work_dir / "hls_validate.json"
    if val_path.is_file():
        validate = json.loads(val_path.read_text(encoding="utf-8"))

    has_cosim = (work_dir / "hls_baseline_cosim.cpp").is_file() and (
        work_dir / "testbench_cosim.cpp"
    ).is_file()

    clock_ns = float(meta.get("target_clock_ns", DEFAULT_CLOCK_NS))
    _write_legacy_tcls(work_dir, clock_ns=clock_ns)
    tcl_paths = emit_autosa_dataset_tcls(work_dir, clock_ns=clock_ns, has_cosim=has_cosim)
    _write_gold_kernel_for_cosim(work_dir)

    bench_id = _bench_id(src_pkg)
    meta = _patch_metadata(
        meta,
        bench_id=bench_id,
        src_pkg=src_pkg,
        validate=validate,
        tcl_paths=tcl_paths,
        has_cosim=has_cosim,
    )
    meta["benchmark"] = bench_id
    meta_path.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    _write_manifest(work_dir)

    return {
        "bench_id": bench_id,
        "src": str(src_pkg),
        "dst": str(work_dir),
        "has_cosim": has_cosim,
        "validate_status": (validate or {}).get("status"),
        "tcl": list(tcl_paths.keys()) + list(LEGACY_TCL),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sources-root", type=Path, default=DEFAULT_SOURCES)
    parser.add_argument("--out-root", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--in-place",
        action="store_true",
        help="Update AutoSA_sources packages in place (also writes dataset_hls*.tcl)",
    )
    parser.add_argument(
        "--copy",
        action="store_true",
        help="Copy files instead of symlinks into --out-root",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Include failed / unvalidated packages (default: ok only)",
    )
    parser.add_argument("--kernels", default="", help="Comma-separated kernel_id filter")
    args = parser.parse_args()

    ok_only = not args.all
    kernel_filter = None
    if args.kernels.strip():
        kernel_filter = [k.strip() for k in args.kernels.split(",") if k.strip()]

    packages = iter_export_packages(args.sources_root, kernel_ids=kernel_filter)
    prepared = []
    skipped = []

    for src_pkg in packages:
        if ok_only:
            val = src_pkg / "hls_validate.json"
            if not val.is_file():
                skipped.append({"pkg": str(src_pkg), "reason": "no hls_validate.json"})
                continue
            status = json.loads(val.read_text()).get("status")
            if status != "ok":
                skipped.append({"pkg": str(src_pkg), "reason": f"status={status}"})
                continue

        bench_id = _bench_id(src_pkg)
        dst_pkg = args.out_root / bench_id
        info = prepare_package(
            src_pkg,
            dst_pkg,
            link=not args.copy,
            in_place=args.in_place,
        )
        prepared.append(info)

        if not args.in_place:
            # Also refresh source metadata for traceability
            prepare_package(src_pkg, src_pkg, in_place=True)

    index = {
        "schema": "benchmarks_autosa_dse_index_v1",
        "created_at": _utc_now(),
        "sources_root": str(args.sources_root.resolve()),
        "out_root": str(args.out_root.resolve()),
        "package_count": len(prepared),
        "skipped_count": len(skipped),
        "benchmarks": prepared,
        "skipped": skipped,
    }
    if not args.in_place:
        args.out_root.mkdir(parents=True, exist_ok=True)
        (args.out_root / "index.json").write_text(json.dumps(index, indent=2) + "\n", encoding="utf-8")

    print(
        json.dumps(
            {
                "prepared": len(prepared),
                "skipped": len(skipped),
                "out_root": str(args.out_root),
                "in_place": args.in_place,
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
